In [ ]:
# NumPy is used over List because :
# > It takes less storage
# > We can perform algorithmic and other mathematical operations on NumPy
# > it provides us wide variety of operations to be performed.
# > it only works for array ( collection of homogeneous datatype)
# > 

In [ ]:
# to convert a list into array, store the array in a variable "x"
x = np.array([list])  

In [5]:
# We can simply perform addition, subtraction, etc
import numpy as np
a = np.array([2,3,4,5])
b = np.array([5,6,7,8])
a+b

array([ 7,  9, 11, 13])

In [8]:
a = np.array([2,3,4,5])
b = np.array([5,1,3,9])
b-a

array([ 3, -2, -1,  4])

In [6]:
import numpy as np
a = np.array([2,4,5,6,7,8])
b = np.array([2,8,8,5,4,3])
# print(a/b,round(2))
a/b

[1.         0.5        0.05102041 0.10714286 1.75       2.66666667] 2


In [8]:
a*b

array([  4,  32, 490, 336,  28,  24])

In [9]:
a**b

array([        4,     65536, -78845287,         0,      2401,       512],
      dtype=int32)

In [12]:
l = [[1,2,3],[2,3,4],[3,4,5]]
arr = np.array(l)
arr.ndim # dimension 2 if two square brackets 3 if  square brackets

2

In [13]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [15]:
arr.shape    #(3 rows and 3 columns)

(3, 3)

In [16]:
arr.size   # total number of elements

9

In [17]:
arr.dtype

dtype('int32')

### Operations in an array

In [ ]:
# addition
# subration
# division
# multiplication

In [5]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a**b

In [21]:
a**b

ValueError: operands could not be broadcast together with shapes (2,4) (6,) 

In [25]:
# can be multiplied or divide by variables
a/10

array([0.1, 0.2, 0.3, 0.4])

In [24]:
a*100+6

array([106, 206, 306, 406])

### comparison operations

In [9]:
a = np.array([2,4,8,34,65,84,4])
a

array([ 2,  4,  8, 34, 65, 84,  4])

In [10]:
a>50

array([False, False, False, False,  True,  True, False])

In [11]:
a[a>50]

array([65, 84])

In [7]:
# to change data types
import numpy as np
c = np.array(a,dtype = float)
c

In [26]:
a<50

array([ True,  True,  True,  True, False, False,  True])

In [27]:
a[a<50]

array([ 2,  4,  8, 34,  4])

In [38]:
#wap to construct a two dimensional array consisting of marks of two students. check in how many subjects student scored 
# above 60
a = np.array([[45,65,98,36],[46,87,56,60]])
a>60
a[a>60]

array([65, 98, 87])

### Logical Operations

In [39]:
a = np.array([[2,5,9,15],[7,9,11,20]])
a

array([[ 2,  5,  9, 15],
       [ 7,  9, 11, 20]])

In [45]:
a[(a>10) & (a>12)]

array([15, 20])

In [46]:
###
a[(a==15) & (a>15) ]

array([], dtype=int32)

In [50]:
a[(a == 11) | (a>15)]

array([11, 20])

In [51]:
~a[(a == 11) | (a>15)]

array([-12, -21], dtype=int32)

In [52]:
a = np.array([[2,5,9,15],[7,9,11,20]])
a

array([[ 2,  5,  9, 15],
       [ 7,  9, 11, 20]])

In [54]:
a.negative()

AttributeError: 'numpy.ndarray' object has no attribute 'negative'

In [55]:
a[a!=20]

array([ 2,  5,  9, 15,  7,  9, 11])

### accessing  array elements

In [57]:
### INDEXING AND SLICING
a


array([[ 2,  5,  9, 15],
       [ 7,  9, 11, 20]])

In [59]:
a[1][2]  # Fetch 11

11

In [60]:
# fetching 9
a[0][2]

9

In [62]:
# fetch   5,9
#         9,11
a[:,1:3]

array([[ 5,  9],
       [ 9, 11]])

In [64]:
a[0:2,1:3]

array([[ 5,  9],
       [ 9, 11]])

In [66]:
b = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
#you have to fetch 6
b

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [71]:
b[0]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [72]:
b[0][0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
b[0][0][1][2]  ## becoz here with first zero we will move inside 1st sq bracket
                #and with second zero we will go inside the 2nd one

6

In [ ]:
# fetch 5,6,8,9

In [74]:
b[0][0][1:3,1:3]

array([[5, 6],
       [8, 9]])

In [75]:
# or
b[0][0][1:,1:]

array([[5, 6],
       [8, 9]])

In [79]:
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [80]:
a.shape

(1, 2, 2, 3)

In [81]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
a.shape

(2, 2, 3)

In [87]:
# two cycles and add their speeds and fetch the values greater than 60
c1 = np.array([10,20,30])
c2 = np.array([20,40,60])
s = c1+c2
s

array([30, 60, 90])

In [88]:
s[s>30]

array([60, 90])

### Class 2

In [10]:
import numpy as np
A = np.array([[234,456,567],[876,654,764]])
A

In [8]:
# to find the last column
A[:,2:3]

NameError: name 'A' is not defined

In [7]:
# To find len( we have to make the array one Dimensional, then only it will give us right value of len(A))
len(A.flatten())    #( basically gives number of elements)

6